apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hextris
  name: hextris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hextris
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hextris
    spec:
      containers:
      - image: dhanrajranvirkar/hextris:87
        name: hextris
        resources: {}
status: {}
