apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hextris
    app.kubernetes.io/instance: hextris
  name: hextris-svc
  namespace: hextris
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hextris
status:
  loadBalancer: {}
